[metadata]
name = tls_synchronization
version = 0.1.0
description = TLS synchronization and open quantum systems simulation tools.
long_description = file: README.md
long_description_content_type = text/markdown
author = 
author_email = 
license = MIT

[options]
packages = find:
package_dir =
    = src
install_requires =
    numpy>=1.26.4
    matplotlib>=3.10.8
    scipy>=1.17.1
    mpmath>=1.4.1
    qutip>=5.2.3
    oqupy>=0.5.0
    tqdm>=4.68.3
python_requires = >=3.11
include_package_data = True

[options.packages.find]
where = src
